---
title: "Population analysis"
author: "Jess Madden"
date: "2/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(here)
library(readxl)
library(janitor)
library(lubridate)
library(kableExtra)
library(ggbeeswarm)
```

Initial wrangling of seine data

```{r}
seine_data <- read.csv(here("data", "Diet_seine_data.csv")) %>% 
  clean_names()

barred <- seine_data %>%   
  filter(common_name == "Barred surfperch") %>% 
  filter(gut_collected == "Yes") %>% 
  filter(site %in% c("Percos", "Refugio", "R Beach")) %>% 
  filter(lifestage %in% c("Adult", "Juvenile")) %>% 
  filter(season %in% c("Summer", "Fall"))


```

Table of fish collected for SCA

```{r}
barred_summary <- barred %>% 
  group_by(site, season) %>% 
  summarise(sample_size = n(), 
            mean_sl = mean(sl_mm), 
            median_sl = median(sl_mm), 
            min_sl = min(sl_mm), 
            max_sl = max(sl_mm))

barred_summary %>% 
  kbl() %>% 
  kable_styling()

ggplot(barred_summary, aes(x = site, y = mean_sl, fill = season)) +
  geom_col(position = "dodge")

ggplot(barred, aes(x = site, y = sl_mm, color = season)) +
  geom_beeswarm() +
  theme_minimal()
```

Histogram of barred surfperch collected for gut analysis

```{r}
ggplot(barred, aes(x = sl_mm)) +
  geom_histogram() +
  facet_grid(season ~ site) +
  theme_minimal()
```

```{r}
#Load data

emerita_pop <- read_xlsx(here("data", "Diet_emerita_population_data_raw.xlsx"), na = "NA") %>% 
  clean_names() %>% 
  filter(site %in% c("Percos", "Refugio", "R Beach")) %>% 
  filter(taxa == "Emerita analoga")
  
```

### Emerita abundance

```{r}
emerita_abundance <- emerita_pop %>% 
  mutate(month = month(date)) %>% 
  mutate(season = case_when(
    month == 6 ~ "Summer", 
    month == 7 ~ "Summer", 
    month == 8 ~ "Summer", 
    month == 9 ~ "Fall", 
    month == 10 ~ "Fall", 
    month == 11 ~ "Fall", 
    month == 12 ~ "Winter", 
    month == 1 ~ "Winter", 
    month == 2 ~ "Winter", 
    month == 3 ~ "Spring",
    month == 4 ~ "Spring",
    month == 5 ~ "Spring"
  ))  #adds in column for season
emerita_abundance$season <- factor(emerita_abundance$season, levels = c("Winter", "Spring", "Summer", "Fall"))
  
emerita_abundance <- emerita_abundance %>% 
  filter(season %in% c("Summer", "Fall")) %>% 
  group_by(site, date, year, season, transect) %>% 
  summarise(abundance = sum(abundance))

emerita_abundance_summary <- emerita_abundance %>% 
  group_by(site, season) %>% 
  summarise(mean_abundance = mean(abundance), 
            se = (sd(abundance))/sqrt(n()), 
            sample_size = n())

emerita_abundance_summary_2020 <- emerita_abundance %>% 
  filter(year == 2020) %>% 
  group_by(site, season) %>% 
  summarise(mean_abundance = mean(abundance), 
            se = (sd(abundance))/sqrt(n()), 
            sample_size = n())

emerita_abundance_summary_2019 <- emerita_abundance %>% 
  filter(year == 2019) %>% 
  group_by(site, season) %>% 
  summarise(mean_abundance = mean(abundance), 
            se = (sd(abundance))/sqrt(n()), 
            sample_size = n())
```

```{r}
emerita_abundance_summary %>% 
  kbl() %>% 
  kable_styling()
```


```{r, fig.width=10}
ggplot(emerita_abundance_summary, aes(x = reorder(site, -mean_abundance), y = mean_abundance, fill = season)) +
  geom_bar(stat = "identity", 
           position = "dodge") +
  geom_errorbar(aes(ymax = mean_abundance+se, 
                    ymin = mean_abundance-se, 
                    fill = season), 
                width = 0.2, 
                position = position_dodge(.9)) +
  theme_minimal() +
  scale_fill_manual("legend", values = c("#657A85", "#354A54")) +
  ylab("Mean E. analoga abundance (m^-1)") +
  xlab("Site")
```
```{r, fig.width=10}
ggplot(emerita_abundance_summary_2019, aes(x = reorder(site, -mean_abundance), y = mean_abundance, fill = season)) +
  geom_bar(stat = "identity", 
           position = "dodge") +
  geom_errorbar(aes(ymax = mean_abundance+se, 
                    ymin = mean_abundance-se, 
                    fill = season), 
                width = 0.1, 
                position = position_dodge(.9)) +
  theme_minimal() + 
  scale_fill_manual("legend", values = c("#657A85", "#354A54")) +
  ylab("Mean E. analoga abundance (m^-1)") +
  xlab("Site") +
  labs(title = "Mean abundance of Emerita analoga in 2019") +
  theme(legend.title = element_blank())  

ggplot(emerita_abundance_summary_2020, aes(x = reorder(site, -mean_abundance), y = mean_abundance, fill = season)) +
  geom_bar(stat = "identity", 
           position = "dodge") +
  geom_errorbar(aes(ymax = mean_abundance+se, 
                    ymin = mean_abundance-se, 
                    fill = season), 
                width = 0.1, 
                position = position_dodge(.9)) +
  theme_minimal() + 
  scale_fill_manual("legend", values = c("#657A85", "#354A54")) +
  ylab("Mean E. analoga abundance (m^-1)") +
  xlab("Site") +
  labs(title = "Mean abundance of Emerita analoga in 2020") +
  theme(legend.title = element_blank())
```

```{r}
emerita_avg_summ <- emerita_abundance %>% 
  group_by(site, season) %>% 
  summarise(mean_abundance = mean(abundance), 
            se = sd(abundance)/sqrt(n()), 
            no_transects = n())
```

```{r, fig.width=10}
ggplot(emerita_avg_summ, aes(x = reorder(site, -mean_abundance), y = mean_abundance, fill = season)) +
  geom_bar(stat="identity", 
           position = "dodge") +
  geom_errorbar(aes(ymax = mean_abundance+se, 
                    ymin = mean_abundance-se, 
                    fill = season), 
                width = 0.2, 
                position = position_dodge(.9)) +
  scale_fill_manual("legend", values = c("#657A85", "#354A54")) +
  ylab("Mean E. analoga abundance (m^-1)") +
  xlab("Site") +
  theme_minimal()

```

### Emerita size distribution


```{r, fig.width=10}
emerita_pop_data <- read_xlsx(here("data", "Diet_emerita_population_data_raw.xlsx"), na = "NA") %>% 
  clean_names() %>% 
  subset(select = -c(22:23)) %>%
  filter(taxa == "Emerita analoga") %>%   
  filter(site %in% c("Percos", "Refugio", "R Beach")) %>% 
  mutate(month = month(date)) %>% 
  mutate(season = case_when(
    month == 6 ~ "Summer", 
    month == 7 ~ "Summer", 
    month == 8 ~ "Summer", 
    month == 9 ~ "Fall", 
    month == 10 ~ "Fall", 
    month == 11 ~ "Fall", 
    month == 12 ~ "Winter", 
    month == 1 ~ "Winter", 
    month == 2 ~ "Winter", 
    month == 3 ~ "Spring",
    month == 4 ~ "Spring",
    month == 5 ~ "Spring"
  )) %>%   #adds in column for season
  filter(season %in% c("Summer", "Fall"))

emerita_pop_data$site <- factor(emerita_pop_data$site, levels = c("Percos", "Refugio", "R Beach"))

perc_emerita <- emerita_pop_data %>% 
  filter(site == "Percos")
refu_emerita <- emerita_pop_data %>% 
  filter(site == "Refugio")
rb_emerita <- emerita_pop_data %>% 
  filter(site == "R Beach")

ggplot(emerita_pop_data, aes(x = width_length_mm)) +
  geom_histogram(aes(y = ..density..), 
                 binwidth = 1, 
                 fill = "#657A85") +
  geom_density(binwidth = 1, 
               outline.type = "full", 
               size = .75, 
               color = "#354A54") +
  theme_minimal() +
  xlim(0, 25) +
  facet_wrap(~site) +
  labs(x = "E. analoga max length (mm)", y = "Frequency", title = "Size distribution of Emerita analoga collected from beach")

ggplot(perc_emerita, 
       aes(x = width_length_mm)) +
  geom_histogram(binwidth = 1, 
                 fill = "#657A85") +
  labs(x = "Emerita size (mm)", y = "Count", title = "Percos") +
  theme_minimal() +
  facet_wrap(~season)

ggplot(refu_emerita, aes(x = width_length_mm)) +
  geom_histogram(binwidth = 1, 
                 fill = "#657A85") +
  labs(x = "Emerita size (mm)", y = "Count", title = "Refugio") +
  theme_minimal() +
  facet_wrap(~season)
ggplot(rb_emerita, aes(x = width_length_mm)) +
  geom_histogram(binwidth = 1, 
                 fill = "#657A85") +
  labs(x = "Emerita size (mm)", y = "Count", title = "R Beach") +
  theme_minimal() +
  facet_wrap(~season)
```










